version: '3'

services:
  app:
    build: 
      context: .
      dockerfile: node/Dockerfile
    depends_on:
      - db
    networks:
      - mysqlnetwork

  nginx:
    build:
      context: nginx
      dockerfile: Dockerfile
    ports:
    - 80:80
    networks:
      - mysqlnetwork


networks:
  mysqlnetwork:
    driver: bridge