version: '3'

services:
  app:
    build: 
      context: node
      dockerfile: Dockerfile
    container_name: app
    entrypoint: dockerize --wait tcp://db:3306 -timeout 20s node index.js
    tty: true
    volumes:
      - ./node/app:/usr/src/app
    depends_on:
      - db
    networks:
      - fcmysqlnetwork

  nginx:
    build:
      context: nginx
      dockerfile: Dockerfile
    container_name: nginx
    ports:
    - "8080:80"
    networks:
      - fcmysqlnetwork

  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    volumes:
      - fcmysqldata:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - fcmysqlnetwork

networks:
  fcmysqlnetwork:
    driver: bridge

volumes:
  fcmysqldata: